### ISSUE TITLE
Credit for test dependencies?

### ISSUE THREAD

**Issue by redbow-kimee** [creditstxt/credit-license#5]
Should credit be given to test dependencies such as unit test frameworks, mocking frameworks, web-drivers, etc? If so does this credit differ from linked and runtime dependencies? How is this credit given?

**Comment by ioistired** [comment]
I am hesitant to say "all tools used to develop the software should be credited" because I feel that that is overly broad. Then you would have to credit your text editor, shell, etc. I think credit for test dependencies should definitely be given, in the same way as runtime dependencies. But I'm not sure how to include such dependencies while excluding personal tooling such as text editors. Maybe we can draw the line by distinguishing "personal dependencies" (deps that vary from person to person) and "software dependencies" (deps that are the same in every environment ie ones explicitly laid out in the code).

**Comment by redbow-kimee** [comment]
I agree that not all tools used make significant (in a sig-figs meaning) contributions. Shell, editor, desktop-environment, kernel, etc are clearly insignificant to most projects. For projects which do use test tools, however, the test tools make a significant contribution, in that without them, there would be significantly more bugs in a given project. In this general sense, the impact of testing tools is measurable.

**Comment by redbow-kimee** [comment]
Question is, whether to credit them just the same as compile time/runtime dependencies, or differently.

**Comment by ioistired** [comment]
I don't see why they should be treated any differently than runtime dependencies. From the perspective of the license, that is an implementation detail.

**Comment by kemitchell** [comment]
Hmm. The relevant language is here:

> ## Credit
> 
> You must give this software and each contributor credit for contribution to other works, be they goods or services, that you produce or provide using this software.

**Comment by kemitchell** [comment]
The language has changed a bit since this issue, but the general gist remains that it doesn't matter _how_ the software is used. If it contributes to a project, credit must be given.
